// Auto-generated by the Supabase CLI/MCP from the live database schema.
// Regenerate after schema changes; do not edit the generated section by hand.
// Convenient row-type aliases are re-exported at the bottom of this file.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      artists: {
        Row: {
          created_at: string
          genre: string | null
          id: string
          image_url: string | null
          is_active: boolean
          lastfm_name: string
          listeners: number | null
          name: string
          playcount: number | null
          slug: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          genre?: string | null
          id?: string
          image_url?: string | null
          is_active?: boolean
          lastfm_name: string
          listeners?: number | null
          name: string
          playcount?: number | null
          slug: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          genre?: string | null
          id?: string
          image_url?: string | null
          is_active?: boolean
          lastfm_name?: string
          listeners?: number | null
          name?: string
          playcount?: number | null
          slug?: string
          updated_at?: string
        }
        Relationships: []
      }
      holdings: {
        Row: {
          artist_id: string
          shares: number
          total_cost_basis: number
          updated_at: string
          user_id: string
        }
        Insert: {
          artist_id: string
          shares?: number
          total_cost_basis?: number
          updated_at?: string
          user_id: string
        }
        Update: {
          artist_id?: string
          shares?: number
          total_cost_basis?: number
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "holdings_artist_id_fkey"
            columns: ["artist_id"]
            isOneToOne: false
            referencedRelation: "artists"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "holdings_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      markets: {
        Row: {
          artist_id: string
          created_at: string
          id: string
          share_reserve: number
          token_reserve: number
          updated_at: string
        }
        Insert: {
          artist_id: string
          created_at?: string
          id?: string
          share_reserve: number
          token_reserve: number
          updated_at?: string
        }
        Update: {
          artist_id?: string
          created_at?: string
          id?: string
          share_reserve?: number
          token_reserve?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "markets_artist_id_fkey"
            columns: ["artist_id"]
            isOneToOne: true
            referencedRelation: "artists"
            referencedColumns: ["id"]
          },
        ]
      }
      price_snapshots: {
        Row: {
          artist_id: string
          created_at: string
          id: number
          price: number
          source: string
        }
        Insert: {
          artist_id: string
          created_at?: string
          id?: never
          price: number
          source: string
        }
        Update: {
          artist_id?: string
          created_at?: string
          id?: never
          price?: number
          source?: string
        }
        Relationships: [
          {
            foreignKeyName: "price_snapshots_artist_id_fkey"
            columns: ["artist_id"]
            isOneToOne: false
            referencedRelation: "artists"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          avatar_url: string | null
          created_at: string
          id: string
          username: string
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string
          id: string
          username: string
        }
        Update: {
          avatar_url?: string | null
          created_at?: string
          id?: string
          username?: string
        }
        Relationships: []
      }
      token_ledger: {
        Row: {
          amount: number
          created_at: string
          id: number
          reason: string
          reference_id: string | null
          user_id: string
        }
        Insert: {
          amount: number
          created_at?: string
          id?: never
          reason: string
          reference_id?: string | null
          user_id: string
        }
        Update: {
          amount?: number
          created_at?: string
          id?: never
          reason?: string
          reference_id?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "token_ledger_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      trades: {
        Row: {
          artist_id: string
          created_at: string
          id: string
          price_per_share: number
          shares: number
          side: string
          tokens: number
          user_id: string
        }
        Insert: {
          artist_id: string
          created_at?: string
          id?: string
          price_per_share: number
          shares: number
          side: string
          tokens: number
          user_id: string
        }
        Update: {
          artist_id?: string
          created_at?: string
          id?: string
          price_per_share?: number
          shares?: number
          side?: string
          tokens?: number
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "trades_artist_id_fkey"
            columns: ["artist_id"]
            isOneToOne: false
            referencedRelation: "artists"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "trades_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      _leaderboard_rows: {
        Args: { p_kind: string }
        Returns: {
          avatar_url: string
          rank: number
          return_pct: number
          total_value: number
          trade_count: number
          user_id: string
          username: string
        }[]
      }
      execute_trade: {
        Args: {
          p_amount: number
          p_artist_id: string
          p_min_receive: number
          p_side: string
          p_user_id: string
        }
        Returns: Json
      }
      get_leaderboard: {
        Args: { p_kind: string; p_limit?: number }
        Returns: {
          avatar_url: string
          rank: number
          return_pct: number
          total_value: number
          user_id: string
          username: string
        }[]
      }
      get_leaderboard_stats: {
        Args: never
        Returns: {
          total_traders: number
          trades_today: number
        }[]
      }
      get_market_overview: {
        Args: never
        Returns: {
          artist_id: string
          current_price: number
          genre: string
          image_url: string
          listeners: number
          name: string
          reference_price: number
          slug: string
        }[]
      }
      get_my_rank: {
        Args: { p_kind: string }
        Returns: {
          avatar_url: string
          rank: number
          return_pct: number
          total_value: number
          trade_count: number
          user_id: string
          username: string
        }[]
      }
      get_portfolio_summary: {
        Args: { p_user_id: string }
        Returns: {
          holdings_value: number
          return_pct: number
          token_balance: number
          total_credited: number
          total_value: number
          user_id: string
        }[]
      }
      get_token_balance: { Args: { p_user_id: string }; Returns: number }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const

// ---------------------------------------------------------------------------
// Convenient row-type aliases.
// These name the `Row` shape of each table so app code can import a single,
// readable type (e.g. `Artist`) instead of `Tables<'artists'>`.
// ---------------------------------------------------------------------------

export type Artist = Tables<"artists">
export type Market = Tables<"markets">
export type Trade = Tables<"trades">
export type Holding = Tables<"holdings">
export type LedgerEntry = Tables<"token_ledger">
export type PriceSnapshot = Tables<"price_snapshots">
export type Profile = Tables<"profiles">

/** Row shape returned by the `get_market_overview` RPC (see its migration). */
export type MarketOverviewRow =
  Database["public"]["Functions"]["get_market_overview"]["Returns"][number]

/** Row shape returned by the `get_portfolio_summary` RPC (see its migration). */
export type PortfolioSummaryRow =
  Database["public"]["Functions"]["get_portfolio_summary"]["Returns"][number]

/** Row shape returned by the `get_leaderboard` RPC (see its migration). */
export type LeaderboardRpcRow =
  Database["public"]["Functions"]["get_leaderboard"]["Returns"][number]

/** Row shape returned by the `get_my_rank` RPC (see its migration). */
export type MyRankRpcRow =
  Database["public"]["Functions"]["get_my_rank"]["Returns"][number]

/** Row shape returned by the `get_leaderboard_stats` RPC (see its migration). */
export type LeaderboardStatsRpcRow =
  Database["public"]["Functions"]["get_leaderboard_stats"]["Returns"][number]
